
trigSF:
    name: Htt_trigSFRDF
    path: Tools.Tools.Htt_trigSF
    parameters:
        year: self.config.year
        isMC: self.dataset.process.isMC
        isUL: self.dataset.has_tag('ul')
        ispreVFP: self.config.get_aux('ispreVFP', False)

# PUjetID_SF:
#     name: PUjetID_SFRDF
#     path: Corrections.JME.PUjetID_SF
#     parameters:
#         year: self.config.year
#         isMC: self.dataset.process.isMC
#         isUL: self.dataset.has_tag('ul')
#         ispreVFP: self.config.get_aux('ispreVFP', False)
#         lep_pt: "{dau1_pt, dau2_pt}"
#         lep_eta: "{dau1_eta, dau2_eta}"
#         lep_phi: "{dau1_phi, dau2_phi}"
#         lep_mass: "{dau1_mass, dau2_mass}"

# 3_w2:
#     name: prescaleWeightRDF
#     path: Tools.Tools.weight
#     parameters:
#         isMC: self.dataset.process.isMC
#         year: self.config.year

# # Only applies to non UL samples
# # 4_w2:
# #     name: prefiringWeightRDF
# #     path: Base.Modules.prefiringWeight
# #     parameters:
# #         isMC: self.dataset.process.isMC
# #         isUL: self.dataset.has_tag('ul')

# muSF:
#     name: muSFRDF
#     path: Corrections.MUO.muCorrections
#     parameters:
#         isMC: self.dataset.process.isMC
#         year: self.config.year
#         isUL: self.dataset.has_tag('ul')
#         ispreVFP: self.config.get_aux('ispreVFP', False)

# eleSD:
#     name: eleSFRDF
#     path: Corrections.EGM.eleCorrections
#     parameters:
#         isMC: self.dataset.process.isMC
#         year: self.config.year
#         isUL: self.dataset.has_tag('ul')
#         ispreVFP: self.config.get_aux('ispreVFP', False)

# idAndIsoSF:
#     name: dauIdIsoSFRDF
#     path: Tools.Tools.dauIdIso
#     parameters:
#         isMC: self.dataset.process.isMC

# btag:
#     name: btag_SFRDF
#     path: Corrections.BTV.btag_SF
#     parameters:
#         isMC: self.dataset.process.isMC
#         year: self.config.year
#         isUL: self.dataset.has_tag('ul')
#         ispreVFP: self.config.get_aux('ispreVFP', False)
#         uncertainties: ["central", "down_hfstats2"]
#         lep_pt: "{dau1_pt, dau2_pt}"
#         lep_eta: "{dau1_eta, dau2_eta}"
#         lep_phi: "{dau1_phi, dau2_phi}"
#         lep_mass: "{dau1_mass, dau2_mass}"

