# Testing of ZH resonant DNN
# Runs the minimum modules to use the DNN

zz:
    name: HHKinFitRDF
    path: Tools.Tools.hh
    parameters:
        isMC: self.dataset.process.isMC
        met_smear_tag: smeared
        AnalysisType: self.config.get_aux('AnalysisType', False)

zzvar:
    name: HHVarRDF
    path: Tools.Tools.hh
    parameters:
        isMC: self.dataset.process.isMC
        met_smear_tag: smeared
        AnalysisType: self.config.get_aux('AnalysisType', False)

# zzdnn:
#     name: HHDNNRDF
#     path: Tools.Tools.HHDNN
#     parameters:
#         isMC: self.dataset.process.isMC
#         year: self.config.year
#         AnalysisType: self.config.get_aux('AnalysisType', False)

zh_res_dnn_500:
    name: HHDNNRDF
    path: Tools.Tools.HHDNN
    parameters:
        isMC: self.dataset.process.isMC
        year: self.config.year
        AnalysisType: self.config.get_aux('AnalysisType', False)
        DNN_res_mass: 500.

zh_res_dnn_1tev:
    name: HHDNNRDF
    path: Tools.Tools.HHDNN
    parameters:
        isMC: self.dataset.process.isMC
        year: self.config.year
        AnalysisType: self.config.get_aux('AnalysisType', False)
        DNN_res_mass: 1000.
