zzdnninputs:
    name: HHDNNInputRDF
    path: Tools.Tools.HHDNN
    parameters:
        isMC: self.dataset.process.isMC
        year: self.config.year
        AnalysisType: self.config.get_aux('AnalysisType', False)