# This configuration is used for PreProcess step
# It is common to all analyses: ZZ, ZH x 2

lumifilter:
    name: lumiFilterRDF
    path: Base.Modules.lumiFilter
    parameters:
        isMC: self.dataset.process.isMC
        year: self.config.year

# UL only
puweightCor:
    name: puWeightRDF
    path: Corrections.LUM.puWeight
    parameters:
        isMC: self.dataset.process.isMC
        year: self.config.year
        isUL: self.dataset.has_tag('ul')

bbtautau_sig_bkg:
    name: BBTauTauFilterRDF
    path: Tools.Tools.ZZ_ZH_Analysis
    parameters:
        ProcType: self.dataset.process.get_aux('ProcType', False)
        isSigBBTT: self.dataset.process.get_aux('isSigBBTT', False)
        isBkgBBTT: self.dataset.process.get_aux('isBkgBBTT', False)

metfilter:
    name: MetFilterRDF
    path: Base.Modules.METfilters
    parameters:
        isMC: self.dataset.process.isMC
        year: self.config.year

# also comutes TES
tauSF:
    name: tauSFRDF
    path: Corrections.TAU.tauCorrections
    parameters:
        isMC: self.dataset.process.isMC
        year: self.config.year
        isUL: self.dataset.has_tag('ul')
        ispreVFP: self.config.get_aux('ispreVFP', False)

# cutflow mutau

hhlepton_skip_mutau_mu_off:
    name: HHLeptonRDF
    path: Tools.Tools.HHLepton
    parameters:
        isMC: self.dataset.process.isMC
        isV10: self.dataset.has_tag("nanoV10")
        year: self.config.year
        runEra: self.dataset.runEra
        vvvl_vsjet: self.config.deeptau.vsjet.VVVLoose
        vl_vse: self.config.deeptau.vse.VLoose
        vvl_vse: self.config.deeptau.vse.VVLoose
        t_vsmu: self.config.deeptau.vsmu.Tight
        vl_vsmu: self.config.deeptau.vsmu.VLoose
        skip_mutau_veto: 1
        skip_mutau_trg: 1
        skip_mutau_dR: 1
        skip_mutau_tau_off: 1
        skip_mutau_mu_off: 1

hhlepton_skip_mutau_tau_off:
    name: HHLeptonRDF
    path: Tools.Tools.HHLepton
    parameters:
        isMC: self.dataset.process.isMC
        isV10: self.dataset.has_tag("nanoV10")
        year: self.config.year
        runEra: self.dataset.runEra
        vvvl_vsjet: self.config.deeptau.vsjet.VVVLoose
        vl_vse: self.config.deeptau.vse.VLoose
        vvl_vse: self.config.deeptau.vse.VVLoose
        t_vsmu: self.config.deeptau.vsmu.Tight
        vl_vsmu: self.config.deeptau.vsmu.VLoose
        skip_mutau_veto: 1
        skip_mutau_trg: 1
        skip_mutau_dR: 1
        skip_mutau_tau_off: 1

hhlepton_skip_mutau_dR:
    name: HHLeptonRDF
    path: Tools.Tools.HHLepton
    parameters:
        isMC: self.dataset.process.isMC
        isV10: self.dataset.has_tag("nanoV10")
        year: self.config.year
        runEra: self.dataset.runEra
        vvvl_vsjet: self.config.deeptau.vsjet.VVVLoose
        vl_vse: self.config.deeptau.vse.VLoose
        vvl_vse: self.config.deeptau.vse.VVLoose
        t_vsmu: self.config.deeptau.vsmu.Tight
        vl_vsmu: self.config.deeptau.vsmu.VLoose
        skip_mutau_veto: 1
        skip_mutau_trg: 1
        skip_mutau_dR: 1

hhlepton_skip_mutau_trg:
    name: HHLeptonRDF
    path: Tools.Tools.HHLepton
    parameters:
        isMC: self.dataset.process.isMC
        isV10: self.dataset.has_tag("nanoV10")
        year: self.config.year
        runEra: self.dataset.runEra
        vvvl_vsjet: self.config.deeptau.vsjet.VVVLoose
        vl_vse: self.config.deeptau.vse.VLoose
        vvl_vse: self.config.deeptau.vse.VVLoose
        t_vsmu: self.config.deeptau.vsmu.Tight
        vl_vsmu: self.config.deeptau.vsmu.VLoose
        skip_mutau_veto: 1
        skip_mutau_trg: 1

hhlepton_skip_mutau_veto:
    name: HHLeptonRDF
    path: Tools.Tools.HHLepton
    parameters:
        isMC: self.dataset.process.isMC
        isV10: self.dataset.has_tag("nanoV10")
        year: self.config.year
        runEra: self.dataset.runEra
        vvvl_vsjet: self.config.deeptau.vsjet.VVVLoose
        vl_vse: self.config.deeptau.vse.VLoose
        vvl_vse: self.config.deeptau.vse.VVLoose
        t_vsmu: self.config.deeptau.vsmu.Tight
        vl_vsmu: self.config.deeptau.vsmu.VLoose
        skip_mutau_veto: 1

# cutflow etau

hhlepton_skip_etau_ele_off:
    name: HHLeptonRDF
    path: Tools.Tools.HHLepton
    parameters:
        isMC: self.dataset.process.isMC
        isV10: self.dataset.has_tag("nanoV10")
        year: self.config.year
        runEra: self.dataset.runEra
        vvvl_vsjet: self.config.deeptau.vsjet.VVVLoose
        vl_vse: self.config.deeptau.vse.VLoose
        vvl_vse: self.config.deeptau.vse.VVLoose
        t_vsmu: self.config.deeptau.vsmu.Tight
        vl_vsmu: self.config.deeptau.vsmu.VLoose
        skip_etau_veto: 1
        skip_etau_trg: 1
        skip_etau_dR: 1
        skip_etau_tau_off: 1
        skip_etau_ele_off: 1

hhlepton_skip_etau_tau_off:
    name: HHLeptonRDF
    path: Tools.Tools.HHLepton
    parameters:
        isMC: self.dataset.process.isMC
        isV10: self.dataset.has_tag("nanoV10")
        year: self.config.year
        runEra: self.dataset.runEra
        vvvl_vsjet: self.config.deeptau.vsjet.VVVLoose
        vl_vse: self.config.deeptau.vse.VLoose
        vvl_vse: self.config.deeptau.vse.VVLoose
        t_vsmu: self.config.deeptau.vsmu.Tight
        vl_vsmu: self.config.deeptau.vsmu.VLoose
        skip_etau_veto: 1
        skip_etau_trg: 1
        skip_etau_dR: 1
        skip_etau_tau_off: 1

hhlepton_skip_etau_dR:
    name: HHLeptonRDF
    path: Tools.Tools.HHLepton
    parameters:
        isMC: self.dataset.process.isMC
        isV10: self.dataset.has_tag("nanoV10")
        year: self.config.year
        runEra: self.dataset.runEra
        vvvl_vsjet: self.config.deeptau.vsjet.VVVLoose
        vl_vse: self.config.deeptau.vse.VLoose
        vvl_vse: self.config.deeptau.vse.VVLoose
        t_vsmu: self.config.deeptau.vsmu.Tight
        vl_vsmu: self.config.deeptau.vsmu.VLoose
        skip_etau_veto: 1
        skip_etau_trg: 1
        skip_etau_dR: 1

hhlepton_skip_etau_trg:
    name: HHLeptonRDF
    path: Tools.Tools.HHLepton
    parameters:
        isMC: self.dataset.process.isMC
        isV10: self.dataset.has_tag("nanoV10")
        year: self.config.year
        runEra: self.dataset.runEra
        vvvl_vsjet: self.config.deeptau.vsjet.VVVLoose
        vl_vse: self.config.deeptau.vse.VLoose
        vvl_vse: self.config.deeptau.vse.VVLoose
        t_vsmu: self.config.deeptau.vsmu.Tight
        vl_vsmu: self.config.deeptau.vsmu.VLoose
        skip_etau_veto: 1
        skip_etau_trg: 1

hhlepton_skip_etau_veto:
    name: HHLeptonRDF
    path: Tools.Tools.HHLepton
    parameters:
        isMC: self.dataset.process.isMC
        isV10: self.dataset.has_tag("nanoV10")
        year: self.config.year
        runEra: self.dataset.runEra
        vvvl_vsjet: self.config.deeptau.vsjet.VVVLoose
        vl_vse: self.config.deeptau.vse.VLoose
        vvl_vse: self.config.deeptau.vse.VVLoose
        t_vsmu: self.config.deeptau.vsmu.Tight
        vl_vsmu: self.config.deeptau.vsmu.VLoose
        skip_etau_veto: 1

# cutflow tautau

hhlepton_skip_tautau_tau_off:
    name: HHLeptonRDF
    path: Tools.Tools.HHLepton
    parameters:
        isMC: self.dataset.process.isMC
        isV10: self.dataset.has_tag("nanoV10")
        year: self.config.year
        runEra: self.dataset.runEra
        vvvl_vsjet: self.config.deeptau.vsjet.VVVLoose
        vl_vse: self.config.deeptau.vse.VLoose
        vvl_vse: self.config.deeptau.vse.VVLoose
        t_vsmu: self.config.deeptau.vsmu.Tight
        vl_vsmu: self.config.deeptau.vsmu.VLoose
        skip_tautau_veto: 1
        skip_tautau_trg: 1
        skip_tautau_dR: 1
        skip_tautau_tau_off: 1

hhlepton_skip_tautau_dR:
    name: HHLeptonRDF
    path: Tools.Tools.HHLepton
    parameters:
        isMC: self.dataset.process.isMC
        isV10: self.dataset.has_tag("nanoV10")
        year: self.config.year
        runEra: self.dataset.runEra
        vvvl_vsjet: self.config.deeptau.vsjet.VVVLoose
        vl_vse: self.config.deeptau.vse.VLoose
        vvl_vse: self.config.deeptau.vse.VVLoose
        t_vsmu: self.config.deeptau.vsmu.Tight
        vl_vsmu: self.config.deeptau.vsmu.VLoose
        skip_tautau_veto: 1
        skip_tautau_trg: 1
        skip_tautau_dR: 1

hhlepton_skip_tautau_trg:
    name: HHLeptonRDF
    path: Tools.Tools.HHLepton
    parameters:
        isMC: self.dataset.process.isMC
        isV10: self.dataset.has_tag("nanoV10")
        year: self.config.year
        runEra: self.dataset.runEra
        vvvl_vsjet: self.config.deeptau.vsjet.VVVLoose
        vl_vse: self.config.deeptau.vse.VLoose
        vvl_vse: self.config.deeptau.vse.VVLoose
        t_vsmu: self.config.deeptau.vsmu.Tight
        vl_vsmu: self.config.deeptau.vsmu.VLoose
        skip_tautau_veto: 1
        skip_tautau_trg: 1

hhlepton_skip_tautau_veto:
    name: HHLeptonRDF
    path: Tools.Tools.HHLepton
    parameters:
        isMC: self.dataset.process.isMC
        isV10: self.dataset.has_tag("nanoV10")
        year: self.config.year
        runEra: self.dataset.runEra
        vvvl_vsjet: self.config.deeptau.vsjet.VVVLoose
        vl_vse: self.config.deeptau.vse.VLoose
        vvl_vse: self.config.deeptau.vse.VVLoose
        t_vsmu: self.config.deeptau.vsmu.Tight
        vl_vsmu: self.config.deeptau.vsmu.VLoose
        skip_tautau_veto: 1

hhlepton:
    name: HHLeptonRDF
    path: Tools.Tools.HHLepton
    parameters:
        isMC: self.dataset.process.isMC
        isV10: self.dataset.has_tag("nanoV10")
        year: self.config.year
        runEra: self.dataset.runEra
        vvvl_vsjet: self.config.deeptau.vsjet.VVVLoose
        vl_vse: self.config.deeptau.vse.VLoose
        vvl_vse: self.config.deeptau.vse.VVLoose
        t_vsmu: self.config.deeptau.vsmu.Tight
        vl_vsmu: self.config.deeptau.vsmu.VLoose

# smearing_SFs:
#     name: jetSmearerRDF
#     path: Corrections.JME.smearing
#     parameters:
#         year: self.config.year
#         isMC: self.dataset.process.isMC
#         jerTag: self.config.year
#         isUL: self.dataset.has_tag('ul')
#         ispreVFP: self.config.get_aux('ispreVFP', False)

# jer_jet:
#     name: jetVarRDF
#     path: Corrections.JME.smearing
#     parameters:
#         isMC: self.dataset.process.isMC

# # also computes up and down variations
# jet_tes_smeared_met:
#     name: metJetTauSmearerRDF
#     path: Corrections.JME.smearing
#     parameters:
#         isMC: self.dataset.process.isMC

# jec_SFs:
#     name: jecProviderRDF
#     path: Corrections.JME.jec
#     parameters:
#         year: self.config.year
#         isMC: self.dataset.process.isMC
#         isUL: self.dataset.has_tag('ul')
#         ispreVFP: self.config.get_aux('ispreVFP', False)
#         # jec_sources: [FlavorQCD, RelativeBal, HF, BBEC1, EC2, Absolute, BBEC1_2018,
#             # EC2_2018, Absolute_2018, HF_2018, RelativeSample_2018, Total]

# jec_jet:
#     name: jecVarRDF
#     path: Corrections.JME.jec
#     parameters:
#         year: self.config.year
#         isMC: self.dataset.process.isMC
#         # jec_sources: [FlavorQCD, RelativeBal, HF, BBEC1, EC2, Absolute, BBEC1_2018,
#             # EC2_2018, Absolute_2018, HF_2018, RelativeSample_2018, Total]

# jec_met:
#     name: jecMETRDF
#     path: Corrections.JME.jec
#     parameters:
#         year: self.config.year
#         isMC: self.dataset.process.isMC
#         # jec_sources: [FlavorQCD, RelativeBal, HF, BBEC1, EC2, Absolute, BBEC1_2018,
#             # EC2_2018, Absolute_2018, HF_2018, RelativeSample_2018, Total]

# hhjets:
#     name: HHJetsRDF
#     path: Tools.Tools.HHJets
#     parameters:
#         year: self.config.year
#         isMC: self.dataset.process.isMC
#         isUL: self.dataset.has_tag('ul')
#         met_smear_tag: smeared
#         filter: True


