puweight:
    name: puWeightRDF
    path: Corrections.LUM.puWeight
    parameters:
        isMC: self.dataset.process.isMC
        year: self.config.year
        isUL: self.dataset.has_tag('ul')

# UL only
# puweightCor:
    # name: puWeightRDF
    # path: Corrections.LUM.puWeightCor
    # parameters:
        # isMC: self.dataset.process.isMC
        # year: self.config.year
        # isUL: self.dataset.has_tag('ul')

dystitching:
    name: DYstitchingEasyRDF
    path: Tools.Tools.dyreweighting
    parameters:
        isDY: self.dataset.process.get_aux('isDY', False)

filter_bbtt:
    name: BBTauTauFilterRDF
    path: Tools.Tools.ZZ_ZH_Analysis
    parameters:
        ProcType: self.dataset.process.get_aux('ProcType', False)
        isSigBBTT: self.dataset.process.get_aux('isSigBBTT', False)
        isBkgBBTT: self.dataset.process.get_aux('isBkgBBTT', False)